from __future__ import annotations

from pathlib import Path

from src.cell_simulation import CellSimulation, scenario_presets
from src.data import RESULTS_DIR, TEX_DIR, write_csv


SIMULATION_SUMMARY_CSV = RESULTS_DIR / "simulation_summary.csv"
SIMULATION_GENERATED_TEX = TEX_DIR / "contents" / "generated-simulation-results.tex"

DEFAULT_TRIALS = 100
DEFAULT_SEED = 20260528


SCENARIO_LABELS = {
    "small_short_lived": "Small short-lived",
    "large_long_lived_naive": "Large long-lived naive",
    "large_slower_division": "Large slower division",
    "large_better_repair": "Large better repair",
    "large_extra_required_hits": "Large extra required hits",
    "large_stronger_immune_control": "Large stronger immune control",
}

SCENARIO_MECHANISMS = {
    "small_short_lived": "lower cell number and shorter exposure time",
    "large_long_lived_naive": "larger cell number and longer exposure time without added protection",
    "large_slower_division": "lower normal-cell division probability",
    "large_better_repair": "higher repair probability for damaged cells",
    "large_extra_required_hits": "higher mutation threshold before cancer transformation",
    "large_stronger_immune_control": "higher initial immune control and killing rate",
}


def simulation_summary_rows(n_trials: int = DEFAULT_TRIALS, seed: int = DEFAULT_SEED) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for index, (scenario, parameters) in enumerate(scenario_presets().items()):
        summary = CellSimulation.run_trials(parameters, n_trials=n_trials, seed=seed + index)
        rows.append({
            "scenario": scenario,
            "label": SCENARIO_LABELS[scenario],
            "mechanism": SCENARIO_MECHANISMS[scenario],
            "n_trials": summary["n_trials"],
            "escape_probability": summary["escape_probability"],
            "mean_escape_time": "" if summary["mean_escape_time"] is None else summary["mean_escape_time"],
            "mean_escape_step": "" if summary["mean_escape_time"] is None else summary["mean_escape_time"],
            "mean_final_cancer_cells": summary["mean_final_cancer_cells"],
            "mean_final_total_cells": summary["mean_final_total_cells"],
            "mean_final_cancer_fraction": summary["mean_final_cancer_fraction"],
        })
    return rows


def write_simulation_artifacts(
    n_trials: int = DEFAULT_TRIALS,
    seed: int = DEFAULT_SEED,
    csv_path: Path = SIMULATION_SUMMARY_CSV,
    tex_path: Path = SIMULATION_GENERATED_TEX,
) -> list[dict[str, object]]:
    rows = simulation_summary_rows(n_trials=n_trials, seed=seed)
    write_csv(csv_path, rows)
    tex_path.parent.mkdir(parents=True, exist_ok=True)
    tex_path.write_text(simulation_summary_tex(rows, n_trials=n_trials, seed=seed), encoding="utf-8")
    return rows


def simulation_summary_tex(rows: list[dict[str, object]], n_trials: int, seed: int) -> str:
    lines = [
        "% Generated by python main.py via src.simulation_exports.write_simulation_artifacts",
        f"% Repeated-trial simulation artifact: n_trials={n_trials}, seed={seed}",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Ringkasan hasil simulasi seluler untuk skenario Peto's Paradox.}",
        "\\label{tab:simulation-summary}",
        "\\resizebox{\\columnwidth}{!}{%",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "Skenario & Escape probability (\\%) & Mean escape step & Mean final cancer fraction (\\%)\\\\",
        "\\midrule",
    ]
    for row in rows:
        escape_probability = 100 * float(row["escape_probability"])
        mean_escape_step = row["mean_escape_step"]
        mean_escape_step_text = "--" if mean_escape_step == "" else f"{float(mean_escape_step):.1f}"
        mean_final_cancer_fraction = 100 * float(row["mean_final_cancer_fraction"])
        lines.append(
            f"{_latex_escape(str(row['label']))} & "
            f"{escape_probability:.1f} & "
            f"{mean_escape_step_text} & "
            f"{mean_final_cancer_fraction:.2f}\\\\"
        )
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "}",
        "\\end{table}",
        f"\\newcommand{{\\SimulationTrialCount}}{{{n_trials}}}",
        f"\\newcommand{{\\SimulationSeed}}{{{seed}}}",
        f"\\newcommand{{\\SimulationScenarioCount}}{{{len(rows)}}}",
        _scenario_command(rows, "large_long_lived_naive", "NaiveEscapeProbability"),
        _scenario_command(rows, "large_stronger_immune_control", "StrongImmuneEscapeProbability"),
    ]
    return "\n".join(lines)


def _scenario_command(rows: list[dict[str, object]], scenario: str, command_name: str) -> str:
    for row in rows:
        if row["scenario"] == scenario:
            return f"\\newcommand{{\\{command_name}}}{{{100 * float(row['escape_probability']):.1f}\\%}}"
    return f"\\newcommand{{\\{command_name}}}{{--}}"


def _latex_escape(value: str) -> str:
    replacements = {
        "&": "\\&",
        "%": "\\%",
        "$": "\\$",
        "#": "\\#",
        "_": "\\_",
        "{": "\\{",
        "}": "\\}",
    }
    return "".join(replacements.get(char, char) for char in value)
